server:
  port: 9000
spring:
  application:
    name: ad-gateway
#eureka: 坑！拒绝连接，原因，少了client
#    service-url:
#      defaultZone: http://localhost:9002/eureka/
eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/
Zuul:
#  前缀，所有经过网关的请求都有这个前缀
  prefix: /cs
#  定义路由
  routes:
    sponsor:
      #识别到这个前缀（/ad-sponsor/**）就会转发到相应的微服务上，**代表匹配任意数量字符+多级目录
      path: /ad-sponsor/**
      #要转发的微服务的名称
      serviceId: eureka-client-ad-sponsor
      #是否跳过前缀
      strip-prefix: false
#      最后实际的url为 127.0.0.1:9000/cs/ad-sponsor/create/adPlan 可以找到对应的配置
