
server:
  port: 7001
  servlet:
    #http controller的请求路径，统一的访问前缀
    context-path: /ad-search

spring:
  application:
    name: eureka-client-ad-search
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ad_data?autoReconnect=true
    username: root
    password: root
    tomcat:
      max-active: 12
      min-idle: 6
      initial-size: 2

#注册到eureka服务器
eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/

#使用feign和hystrix
feign:
  hystrix:
    enabled: true

#对项目进行监控,*代表暴露全部监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"

# 定义MySQL相关配置,后续用于让BinLog读取配置文件，拿到配置参数
adconf:
  mysql:
    host: 127.0.0.1
    port: 3306
    username: root
    password: root
    binlogName: ""
#    -1代表从当前开始监听
    position: -1

  kafka:
    topic: ad-search-mysql-data
